### ISSUE TITLE
[Summer2022] 大家好！请问“利用 OpenSumi 实现 IDE 模式的 Github CodeReview 功能”这个feat最后会合入这个仓库吗？

### ISSUE THREAD

**Issue by tyn1998** [opensumi/ide-startup-lite#13]
标题有点长哈~是关于opensumi在Summer2022中的[这个项目](https://summer-ospp.ac.cn/#/org/prodetail/22dca0048)：
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/32434520/168216232-9f18e0c1-ac4f-40aa-8ed7-8477da0a9769.png">

**Comment by Aaaaash** [comment]
如果项目成果是一个独立的模块，则需要在这个仓库中集成一下，具体来说就是将 codereview-module 引入进来

**Comment by tyn1998** [comment]
谢谢回复！我看到opensumi下有好多仓库了，我会去了解一下仓库间的关系~

**Comment by Aaaaash** [comment]
可以参考一下 [opensumi-module-samples](https://github.com/opensumi/opensumi-module-samples/tree/main/connection-sample) 里的模块示例

**Comment by tyn1998** [comment]
OK~
