### ISSUE TITLE
提示@opensumi/ide-core-common/lib/path不存在呢

### ISSUE THREAD

**Issue by mindops** [opensumi/ide-startup-lite#20]
ModuleNotFoundError: Module not found: Error: Can't resolve '@opensumi/ide-core-common/lib/path' in '/xxx/ide-startup-lite/web-lite/file-provider'

<img width="1766" alt="image" src="https://user-images.githubusercontent.com/6076639/175515011-8663642f-6b3b-4d2e-8bda-5e62322dc61e.png">

**Comment by AhkunTa** [comment]
升级opensumi版本问题导致的问题 #19 已经修复
