### ISSUE TITLE
内网本地化部署，有哪些CDN资源需要本地化

### ISSUE THREAD

**Issue by naduohua** [opensumi/ide-startup-lite#25]
web-lite的demo从alicdn、alipayobjects请求了部分资源文件，内网无法请求这些资源。
1、需要本地部署的资源有哪些
2、需要修改或重写的配置文件、方法有哪些

**Comment by erha19** [comment]
@naduohua  对于部分希望自主托管的 CDN 资源，可以直接请求文件内容后自行托管，插件部分引入的为 `Web Extensions` ，这部分资源与 VS Code 内 [web-extensions](https://code.visualstudio.com/api/extension-guides/web-extensions) 是兼容的，可以自行下载后进行托管，相关代码见：

https://gitlab.alibaba-inc.com/tao-ide/code-lite/blob/11c481e10fa9fb8a4e0fd92f40417e01add01aca/web-lite/extension/index.ts#L5

**Comment by fankangsong** [comment]
> @naduohua 对于部分希望自主托管的 CDN 资源，可以直接请求文件内容后自行托管，插件部分引入的为 `Web Extensions` ，这部分资源与 VS Code 内 [web-extensions](https://code.visualstudio.com/api/extension-guides/web-extensions) 是兼容的，可以自行下载后进行托管，相关代码见：
> 
> https://gitlab.alibaba-inc.com/tao-ide/code-lite/blob/11c481e10fa9fb8a4e0fd92f40417e01add01aca/web-lite/extension/index.ts#L5

@erha19 嗨，这个文件好想无法访问，请问可以贴一下具体的代码吗？
