### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by mbpz** [opensumi/ide-startup-lite#3]
![image](https://user-images.githubusercontent.com/19383199/156523508-ca3729d2-7578-4544-8914-e524ded494ca.png)

**Comment by bytemain** [comment]
这个看报错是 node-gyp 相关的报错。在构建 native module 时报的错。

这个错误是由于使用了 python3 运行 python2 脚本，应该是 node-gyp 环境没有配置好。

请参见：https://github.com/nodejs/node-gyp#on-windows
