### ISSUE TITLE
编译 webworker 插件环境 报错

### ISSUE THREAD

**Issue by Sermonizer** [opensumi/ide-startup-lite#4]
![9d9d795925c85d170722efce46d4fe7](https://user-images.githubusercontent.com/24455646/156528211-a574adf7-700b-4fa7-9519-eb79049ec5ce.png)

**Comment by bytemain** [comment]
这是由于 `NODE_ENV=xxx` 是在 Unix 下设置环境变量的方式，windows 下需要用 `set XX=xx`。

可以先将 `package.json` 中的这个 scripts 脚本设置成 `set NODE_ENV=production XXXX`

我们稍后修复这个问题。
