### ISSUE TITLE
请问怎么写Dockerfile?

### ISSUE THREAD

**Issue by c21xdx** [opensumi/ide-startup-lite#43]
我按照Quick Start写了一个，推到docker hub成功了，然后在VPS上pull下来安装就是启动不起来，好像是提是 在/目录下找不到package.json。这个要怎么写才对？

`
FROM node:14-bullseye

USER root

RUN apt-get update && \
    git clone https://github.com/opensumi/ide-startup-lite.git && cd ide-startup-lite && \
    yarn && apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*
    
EXPOSE 8081
    
CMD yarn start

`

**Comment by erha19** [comment]
@c21xdx 这块可以参考一下网上的一些资料 https://nodejs.org/zh-cn/docs/guides/nodejs-docker-webapp/ ，同时，不建议使用 `yarn start` 作为启动入口，这块可以自己尝试一下。
