### ISSUE TITLE
expolor 下面挂的组件过多会出现问题

### ISSUE THREAD

**Issue by web3creator** [opensumi/ide-startup-lite#47]
<img width="501" alt="截屏2023-03-03 14 09 48" src="https://user-images.githubusercontent.com/52997135/222644731-41908d3c-e85c-42e4-8eb4-dff1103139e6.png">

**Comment by erha19** [comment]
@web3creator 确实有这个问题，但目前不建议在一个面板下挂载过多视图，这种交互明显不符合用户使用习惯
