### ISSUE TITLE
复制功能不可用

### ISSUE THREAD

**Issue by web3creator** [opensumi/ide-startup-lite#48]
目前的复制文件、或者文件夹是不是在web端没开放，我断点测试 copy 函数是没有触发的 是我的使用方式有问题吗

**Comment by erha19** [comment]
@web3creator 目前是支持的，如有问题，麻烦提供一下录屏或复现路径

**Comment by web3creator** [comment]
Uploading 屏幕录制2023-03-07 18.25.42.mov…
![截屏2023-03-07 18 27 26](https://user-images.githubusercontent.com/52997135/223395665-c8280a0c-9766-4c4d-a66a-9b175bd6d49c.png)

这个copy 函数没有触发。我看着是复制的时候  读了一下目的 文件 没有读原始文件路径
@erha19

**Comment by erha19** [comment]
@web3creator 抱歉，看错项目了，纯前端的项目默认没有实现“复制-粘贴” 功能，只实现了简单的文件读取能力，如果需要实现，需要对相关的文件服务进行实现，如这里的复制操作是在前端实现的数据缓存，你需要断点在粘贴文件这步，可以断点一下
`file-tree-api.service.js` 里面的 `copyFile` 方法。

**Comment by web3creator** [comment]
@erha19 我找到了 我看看改下 fs-browser的实现，th
