### ISSUE TITLE
Ubuntu后台服务器安装-浏览器访问失败

### ISSUE THREAD

**Issue by liweijian** [opensumi/ide-startup-lite#54]
把 ide-startup-lite 安装在 Ubuntu 后台服务器

## 防火墙测试通过

```
python3 -m http.server 8080
```

显示：
<img width="300" alt="image" src="https://user-images.githubusercontent.com/19320783/232372345-35ecfc5c-53bd-4829-91d9-73ce58253b50.png">

## ide-startup-lite 测试

当前只修改了端口，从默认的 8081 改成了 8080:

```
ubuntu@ub01:~/ide-startup-lite$ grep "8080" webpack.lite.config.js
const port = 8080;
```

根据[这个指引](https://opensumi.com/zh/docs/integrate/quick-start/lite#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)执行:

```
$ npm run start 

> ide-startup-lite@0.0.1 start
> webpack-dev-server --config ./webpack.lite.config.js

ℹ ｢wds｣: Project is running at http://127.0.0.1:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/ubuntu/ide-startup-lite/dist


 WARNING  Compiled with 2 warnings                                                                                            3:41:12 AM

 warning  in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/performance.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/@opensumi/monaco-editor-core/esm/vs/base/common/performance.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

⚠ ｢wdm｣: Hash: 98b5e769c51dfbf89e19
Version: webpack 4.46.0
Time: 23801ms
Built at: 04/17/2023 3:41:12 AM
```

## 浏览器访问测试 - 失败
<img width="600" alt="image" src="https://user-images.githubusercontent.com/19320783/232372775-45cc49a4-82b6-4f26-aa81-c91082def8ce.png">

## 同一台服务器wget测试 - 成功
<img width="600" alt="image" src="https://user-images.githubusercontent.com/19320783/232372919-9ed22d2e-ee7c-439b-9342-7cc3e506ddb3.png">

是什么步骤漏了吗?

**Comment by erha19** [comment]
@liweijian 你这里的 `npm run start` 是开发流程，如果是部署的话，你可以参考这个步骤：

```yaml
npm
npm run compile:ext-worker
npm run build
```

之后的静态文件会被构建在 `./dist` 目录下，你将这个目录挂载为静态资源，自定义访问端口，即可正常访问。

**Comment by liweijian** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/19320783/232374040-a835f1f3-594f-4172-a34d-3e01866bb833.png">

@erha19 确实可以访问了，但是为啥是一片空白？（端口是iptable映射，不影响）

后台提示：
<img width="880" alt="image" src="https://user-images.githubusercontent.com/19320783/232374157-b63c47bd-9953-4f6e-86bb-3ac80f13b6d0.png">

**Comment by liweijian** [comment]
换成 serve 同样失败(`serve dist -l 8080`):
<img width="853" alt="image" src="https://user-images.githubusercontent.com/19320783/232380018-12004006-35a8-41a5-95fa-0f8158e38fc4.png">

**Comment by liweijian** [comment]
搞定了，翻了一下代码，发现需要手工修改 `cdnBase`，把 `ide-startup-lite` 改成 `''` 就没有问题了
<img width="500" alt="企业微信截图_0820faaf-3a46-437d-8ea2-d2090cbb2388" src="https://user-images.githubusercontent.com/19320783/232396828-c2d123e8-1d16-4c6d-8474-d07c49d3e7b7.png">



<img width="477" alt="image" src="https://user-images.githubusercontent.com/19320783/232396662-8164a0db-195d-4456-b6b2-2befd8e810fe.png">
