### ISSUE TITLE
在src/module/index.contribution.ts里导入FileTreeModelService报错

### ISSUE THREAD

**Issue by hanlin77** [opensumi/ide-startup-lite#77]
导入方式：
import { FileTreeModelService } from '@opensumi/ide-file-tree-next/src/browser/services/file-tree-model.service';

报错截图：
<img width="954" alt="L1VzZXJzL2hhbmxpbi9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvRGluZ1RhbGtNYWMvMTQ5MDI4OTZfdjIvSW1hZ2VGaWxlcy8xNzEwMzk5OTkwNTExX+aIquWxjzIwMjQtMDMtMTQg5LiL5Y2IMy4wNi4yNi5wbmc=" src="https://github.com/opensumi/ide-startup-lite/assets/39614005/233e49fb-824a-4056-bff9-1ce4cac62b90">

**Comment by bytemain** [comment]
opensumi 在这里有一个循环引用，之后我们修复一下。

你这里直接引用了 `src` 下面的路径，试一下改成引用 `lib` 下的

试一下：
```
import { FileTreeModelService } from '@opensumi/ide-file-tree-next/lib/browser/services/file-tree-model.service';
```
